let products = [
  {
    name: "Apple MacBook Pro 2021",
    series: "MacBook Pro 2021",
    id: "Apple-MacBook-Pro-2021",
    price: "2,899",
    brand: "Apple",
    hardDiskSize: "512 GB",
    CPUModel: "ARM 7100",
    cardDescription: "Dedicated",
    graphicsCoprocessor: "M1 Pro",
    ramMemorySize: "16 GB",
    operatingSystem: "MacOS 12 Monterey",
    percentDiscount: null,
    previousPrice: null,
    score: 4.7,
    image: "Apple-MacBook-Pro-2021.jpg",
    color: ["#9e9e9e"],
    colorText: ["Gray"],
    model: "MK193",
    screenSize: 16.2,
  },
  {
    name: "Asus ROG Strix SCAR 15",
    series: "ROG Strix SCAR 15",
    id: "Asus-ROG-Strix-SCAR-15",
    price: "2,499",
    brand: "Asus",
    hardDiskSize: "1 TB",
    CPUModel: "Intel Core i9 12900H",
    cardDescription: "RTX 3080",
    graphicsCoprocessor: "NVIDIA GeForce RTX 3080",
    ramMemorySize: "16 GB",
    operatingSystem: "Windows 11 Home",
    percentDiscount: null,
    previousPrice: null,
    score: 4.5,
    image: "Asus-ROG-Strix-SCAR-15.jpg",
    color: ["#212121", "#443b3c", "#002171"],
    colorText: ["Black,", "Brown,", "Dark blue"],
    model: "G513IE-HN060",
    screenSize: 15.6,
  },
  {
    name: "Lenovo Legion 7",
    series: "Legion 7",
    id: "Lenovo-Legion-7",
    price: "2,449",
    brand: "Lenovo",
    hardDiskSize: "2 TB",
    CPUModel: "Intel Core i9 11980HK",
    cardDescription: "RTX 3080",
    graphicsCoprocessor: "NVIDIA GeForce RTX 3080",
    ramMemorySize: "32 GB",
    operatingSystem: "Windows 11 Home",
    percentDiscount: 16,
    previousPrice: "2,899",
    score: 4.3,
    image: "Lenovo-Legion-7.jpg",
    color: ["#9e9e9e"],
    colorText: ["Gray"],
    model: "16ITHg6",
    screenSize: 16,
  },
  {
    name: "Acer Nitro 5",
    series: "Nitro 5",
    id: "Acer-Nitro-5",
    price: "2,649",
    brand: "Acer",
    hardDiskSize: "1 TB",
    CPUModel: "AMD Ryzen 9 5900HX",
    cardDescription: "RTX 3080",
    graphicsCoprocessor: "NVIDIA GeForce RTX 3080",
    ramMemorySize: "32 GB",
    operatingSystem: "Windows 11 Home",
    percentDiscount: null,
    previousPrice: null,
    score: 4.8,
    image: "Acer-Nitro-5.jpg",
    color: ["#002171", "#212121"],
    colorText: ["Dark blue,", "Black"],
    model: "AN515-45-R6WC",
    screenSize: 15.6,
  },
  {
    name: "MSI Creator Z16",
    series: "Creator Z16",
    id: "MSI-Creator-Z16",
    price: "2,300",
    brand: "MSI",
    hardDiskSize: "1.5 TB",
    CPUModel: "Intel Core i7 12700H",
    cardDescription: "RTX 3050",
    graphicsCoprocessor: "NVIDIA GeForce RTX 3050",
    ramMemorySize: "32 GB",
    operatingSystem: "Windows 11 Home",
    percentDiscount: 12,
    previousPrice: "2,599",
    score: 4.3,
    image: "MSI-Creator-Z16.jpg",
    color: ["#dedede"],
    colorText: ["Light gray"],
    model: "A12UET",
    screenSize: 16,
  },
];

export function getProducts() {
  return products;
}

export function getProduct(id) {
  return products.find(
    (product) => product.id === id
  );
}